export const QUERIES = {
  financials: `SELECT MONTH_END_DT, ACCOUNT_TYPE,
    COALESCE(C_REVENUE,'') as C_REVENUE,
    COALESCE(C_PARENT_DEPT,'') as C_PARENT_DEPT,
    COALESCE(C_PL_CLASS,'') as C_PL_CLASS,
    COALESCE(C_EXPENSE_CATEGORY,'') as C_EXPENSE_CATEGORY,
    CASE WHEN C_REVENUE = 'Services Revenue' THEN COALESCE(ACCOUNT_NBR,'') ELSE '' END as ACCOUNT_NBR,
    SUM(AMT) as AMT
  FROM load.finance_sandbox.mrp_financials
  WHERE MONTH_END_DT BETWEEN '2025-06-30' AND '2026-05-31' AND C_PL_INCLUDE = TRUE
  GROUP BY MONTH_END_DT,ACCOUNT_TYPE,C_REVENUE,C_PARENT_DEPT,C_PL_CLASS,C_EXPENSE_CATEGORY,
    CASE WHEN C_REVENUE = 'Services Revenue' THEN COALESCE(ACCOUNT_NBR,'') ELSE '' END
  ORDER BY MONTH_END_DT,ACCOUNT_TYPE`,

  budget: `SELECT TIME_MONTH_END,
    COALESCE(C_REVENUE,'') as C_REVENUE,
    COALESCE(C_PARENT_DEPT,'') as C_PARENT_DEPT,
    COALESCE(C_PL_CLASS,'') as C_PL_CLASS,
    COALESCE(C_EXPENSE_CATEGORY,'') as C_EXPENSE_CATEGORY,
    COALESCE(ACCOUNT_CODE,'') as ACCOUNT_CODE,
    SUM(VALUE) as BUDGET
  FROM load.finance_sandbox.mrp_forecast
  WHERE VERSION_NAME = '2026.3.6 - FY27 Final BoD Approved' AND C_PL_INCLUDE = 1
    AND (C_REVENUE IS NOT NULL AND C_REVENUE != '' OR C_PARENT_DEPT IS NOT NULL AND C_PARENT_DEPT != '')
  GROUP BY TIME_MONTH_END,C_REVENUE,C_PARENT_DEPT,C_PL_CLASS,C_EXPENSE_CATEGORY,ACCOUNT_CODE
  HAVING TIME_MONTH_END IN (
    TO_DATE('2026-02-28','YYYY-MM-DD'),TO_DATE('2026-03-31','YYYY-MM-DD'),
    TO_DATE('2026-04-30','YYYY-MM-DD'),TO_DATE('2026-05-31','YYYY-MM-DD'))
  ORDER BY TIME_MONTH_END`,

  arr: `SELECT MONTH_END_DT, SUM(C_ARR) as C_ARR, SUM(NEW_ARR) as NEW_ARR,
    SUM(EXPANSION_ARR) as EXP_ARR, SUM(CHURN_ARR) as CHURN_ARR,
    SUM(UP_FOR_RENEWAL_ARR) as UP_RENEWAL, SUM(RENEWED_ARR) as RENEWED_ARR
  FROM prod.dealsbase.customer_month
  WHERE MONTH_END_DT BETWEEN '2026-01-31' AND '2026-05-31'
  GROUP BY MONTH_END_DT ORDER BY MONTH_END_DT`,

  cash: `SELECT MONTH_END_DATE, ACCOUNT_CATEGORY, SUM(ENDING_BALANCE) as BALANCE
  FROM load.finance_sandbox.mrp_cash
  WHERE MONTH_END_DATE BETWEEN '2026-01-31' AND '2026-05-31'
    AND ACCOUNT_CATEGORY IN ('Cash','Equity')
  GROUP BY MONTH_END_DATE, ACCOUNT_CATEGORY ORDER BY MONTH_END_DATE`,

  billings: `SELECT INVOICED_ACCOUNTING_PERIOD as PERIOD, SUM(INVOICE_AMOUNT_USD) as AMOUNT
  FROM load.finance_sandbox.mrp_billings_collections
  WHERE INVOICED_ACCOUNTING_PERIOD BETWEEN '2026-02-28' AND '2026-05-31'
  GROUP BY PERIOD ORDER BY PERIOD`,

  collections: `SELECT COLLECTED_ACCOUNTING_PERIOD as PERIOD, SUM(COLLECTION_AMOUNT_USD) as AMOUNT
  FROM load.finance_sandbox.mrp_billings_collections
  WHERE COLLECTED_ACCOUNTING_PERIOD BETWEEN '2026-02-28' AND '2026-05-31'
  GROUP BY PERIOD ORDER BY PERIOD`,

  sales: `SELECT CLOSE_MONTH, OPPORTUNITY_OWNER, COALESCE(ACCOUNT_RVP,'') as ACCOUNT_RVP, SUM(CLOSED_ARR) as CLOSED_ARR
  FROM load.finance_sandbox.mrp_sales_effect
  WHERE CLOSE_MONTH BETWEEN '2026-02-28' AND '2026-05-31'
    AND (REP_TYPE IN ('AE','RVP') OR OPPORTUNITY_OWNER = ACCOUNT_RVP)
  GROUP BY CLOSE_MONTH,OPPORTUNITY_OWNER,ACCOUNT_RVP ORDER BY ACCOUNT_RVP,OPPORTUNITY_OWNER,CLOSE_MONTH`,

  headcount: `SELECT COALESCE(C_PARENT_DEPT,'Unassigned') as DEPT, EMPLOYEE_TYPE,
    SUM("2025-06-30") as HC_JUN25, SUM("2025-07-31") as HC_JUL25,
    SUM("2025-08-31") as HC_AUG25, SUM("2025-09-30") as HC_SEP25,
    SUM("2025-10-31") as HC_OCT25, SUM("2025-11-30") as HC_NOV25,
    SUM("2025-12-31") as HC_DEC25, SUM("2026-01-31") as HC_JAN26,
    SUM("2026-02-28") as HC_FEB26, SUM("2026-03-31") as HC_MAR26,
    SUM("2026-04-30") as HC_APR26, SUM("2026-05-31") as HC_MAY26
  FROM load.finance_sandbox.mrp_employee_snap
  GROUP BY C_PARENT_DEPT,EMPLOYEE_TYPE ORDER BY DEPT,EMPLOYEE_TYPE`,

  hcBridge: `SELECT 'Hire' as EVT, COALESCE(C_PARENT_DEPT,'') as DEPT, COUNT(*) as CNT
  FROM load.finance_sandbox.mrp_employee_snap WHERE START_DT BETWEEN '2026-05-01' AND '2026-05-31'
  GROUP BY C_PARENT_DEPT UNION ALL
  SELECT TERMINATED_REASON, COALESCE(C_PARENT_DEPT,''), COUNT(*)
  FROM load.finance_sandbox.mrp_employee_snap
  WHERE DEPARTURE_DT BETWEEN '2026-05-01' AND '2026-05-31'
    AND TERMINATED_REASON IS NOT NULL AND TERMINATED_REASON!=''
  GROUP BY TERMINATED_REASON,C_PARENT_DEPT`,

  salesTargets: `SELECT ROLE_TYPE, NAME, MANAGER_NAME, MONTH_START, SUM(MONTHLY_QUOTA_FROM_PRORATED) as TARGET
  FROM load.finance_sandbox.mrp_sales_targets
  WHERE MONTH_START IN ('2026-02-01','2026-03-01','2026-04-01','2026-05-01')
    AND ROLE_TYPE IN ('AE','RVP') AND (IS_ACTIVE = TRUE OR IS_ACTIVE IS NULL)
  GROUP BY ROLE_TYPE, NAME, MANAGER_NAME, MONTH_START ORDER BY ROLE_TYPE, NAME, MONTH_START`,

  hcBudgetDept: `SELECT C_PARENT_DEPT, SUM(VALUE) as BUDGET
  FROM load.finance_sandbox.mrp_forecast
  WHERE VERSION_NAME = '2026.3.6 - FY27 Final BoD Approved'
    AND ACCOUNT_CODE = 'Total_HC_EOM' AND C_PARENT_DEPT IS NOT NULL AND C_PARENT_DEPT != ''
    AND TIME_MONTH_END = TO_DATE('2026-05-31','YYYY-MM-DD')
  GROUP BY C_PARENT_DEPT`,

  kpi: `SELECT TIME_MONTH_END, ACCOUNT_CODE, SUM(VALUE) as BUDGET
  FROM load.finance_sandbox.mrp_forecast
  WHERE VERSION_NAME = '2026.3.6 - FY27 Final BoD Approved'
    AND ACCOUNT_CODE IN ('Adjusted_CF','KPI.NewARR','KPI.ExpansionARR','KPI.Downsell_Churn',
      'Cash_EOP','Total_HC_EOM','KPI.Exiting_ARR','Bookings.UpForRenewal',
      'BillCollect.Billings','BillCollect.Collections')
  GROUP BY TIME_MONTH_END, ACCOUNT_CODE
  HAVING TIME_MONTH_END IN (
    TO_DATE('2026-02-28','YYYY-MM-DD'),TO_DATE('2026-03-31','YYYY-MM-DD'),
    TO_DATE('2026-04-30','YYYY-MM-DD'),TO_DATE('2026-05-31','YYYY-MM-DD'))
  ORDER BY ACCOUNT_CODE, TIME_MONTH_END`,
};
